### ISSUE TITLE
Allow multiple columns with same column name

### ISSUE THREAD

**Issue by floriansattler** [sphereio/csv-mapper#8]
It would be important to handle columns with same name in the csv-mapper.

Use case is to provide additional image links for a datafeed for google merchant center. Google always expects the same header additional_image_link.

The following code for example creates two additional_image_link columns but all of the containing URLs end with "-3"  instead of "-1" and "-3"

``` yaml
  -
    type: "addColumn"
    toCol: "additional_image_link"
    valueTransformers:
      -
        type: "multipartString"
        parts:
          -
            valueTransformers:
              -
                type: "constant"
                value: "https://coeur.scene7.com/is/image/Coeur/"
          -
            valueTransformers:
              -
                type: "column"
                col: "ID"
          -
            valueTransformers:
              -
                type: "constant"
                value: "-1"
# setze zusätzliche Bild-Url aus Media-Url und SKU und -3 zusammen  
  -
    type: "addColumn"
    toCol: "additional_image_link"
    valueTransformers:
      -
        type: "multipartString"
        parts:
          -
            valueTransformers:
              -
                type: "column"
                col: "Media-Url"
          -
            valueTransformers:
              -
                type: "column"
                col: "ID"
          -
            valueTransformers:
              -
                type: "constant"
                value: "-3"
```
